Meet the team
HackNC/fall2024 pull request #13
Opened 2024-06-23 20:08 UTC by vvkash

Added Meet The Team page and Link to it in the nav bar, also changed the file location.

Had to make another pull request, the other one was having issues lol

2024-06-27 16:40 UTC, rishyendra333 requested changes

2024-06-27 16:40 UTC, rishyendra333 commented on index.html
> +            <li id="nav-section"><a href="#meettheteam">Meet The Team</a></li>
change the href from #meettheteam to /meet-the-team/index.html to link to that page.

2024-06-27 19:09 UTC, aryasalian commented
I went over your code and fixed what rishi had asked for. There are still some issues with it and I tried fixing it as much as possible but I'll let you take over it again now. I noticed the slider would go way beyond where it's supposed to end so I tried to make some edits to your slider. There is a considerable amount of improvement but I need you to look into why the transformX isn't working accurately at different window sizes. It sometimes cuts the images or overshoots the scroll even though I've tried reducing that issue as much as possible. Focus on the line that causes the scroll, it's to do with the math of it.

2024-06-28 02:26 UTC, vvkash commented
Yeah i see, i totally mislooked that haha. im refactoring right now and i think i got the issue where it overshoots and the issue with different window sizes. though for some reason the updated code wont allow me to click the arrows to scroll through, ive checked the event listeners as well. If its okay with everyone, i can implement all the changes you've done and the new updates to the sizing and issues but keep some of the arrow functionality and then commit again? lmk if this works and ill get it done and commit it this week!

2024-06-28 02:41 UTC, vvkash commented
Also just to make sure, you want to keep the picture sizing the same even when the window itself is being changed right? also is there a certain sizing guide you want me to impliment and follow for the slider? Thanks!

2024-06-28 14:04 UTC, aryasalian commented
For the arrow functionality, it works as it is supposed to when I put my commits in...it is not supposed to scroll ahead if the last image in the slider is visible and at a normal window size, since we only have 3 images in the slider currently, the third image is visible in the slider by default so it seems that the arrow doesn't work but if you try and shrink the window to only keep one or two or even two and a fraction image visible, the scrolling functionality will work. It's the math of how many times should you be allowed to click the arrow for scrolling to the end is what needs to be fixed because as I said, when I was working with it, it either overshot it or didn't let you scroll enough.

As for the image size I think it is smart to have the image shrink to scale with window size since that would make all this much easier and we can instead just code each slider's arrow to be allowed to be clicked a fixed number of times instead of making it dependent on the no. of visible images/total images in the slider. Ensure that after a certain small window size, the slider just disappears entirely since having super tiny images wouldn't help anyways

2024-06-28 14:04 UTC, aryasalian commented
Good work on most of the stuff tho!

2024-07-04 14:20 UTC, aryasalian commented
Seems good to me now but the button for junior director slider just moves with the images lol. Try and fix that. The meet the team tab on the landing page needs to be resized when the window resized. Please add a commit for that in this branch itself. Make sure the resizing works for the mobile-view's hamburger dropdown as well. Everything else looks great!

2024-07-07 03:38 UTC, vvkash commented
Fixed The Issue with the slider arrow and will work on adding the logo for the home link and adding the arrows to the border of the sliders in the next few days. Been out of town so havent been able to finish that! Also will fix the resizing issue regarding the meet the team logo and the hamburger menu by next  week as well.

2024-07-14 07:49 UTC, merged